### ISSUE TITLE
Testing, No module named 'database'

### ISSUE THREAD

**Issue by Barceloch** [ArcArcaman/Flask-MVC#1]
$ python src/server.py 
Traceback (most recent call last):
  File "src/server.py", line 12, in <module>
    import database.connections as dbconn
ModuleNotFoundError: No module named 'database'

database is a file .py or I need some paquet?. in the project is important the requeriment.txt files for test.

**Comment by ArcArcaman** [comment]
Thanks for raising the issue, will look into it and get back to you as soon as possible.

**Comment by ArcArcaman** [comment]
Solved issue on commit 2b87751a0ed6a0a65edbb43236dd5b2a6d9a6ee3

**Comment by ArcArcaman** [comment]
Added requirements.txt.
Commit in: 367db0ea09ab902e717fa57bb5555c7fc7c86ead
